Desktop/Ruby/Ruby_on_Rails_Project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end
  
  root 'posts#index'

  get '/posts/mypost/:id', to: 'posts#mypost', as: 'mypost'
end

Desktop/Ruby/Ruby_on_Rails_Project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Desktop/Ruby/Ruby_on_Rails_Project/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

Desktop/Ruby/Ruby_on_Rails_Project/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :title, :description, :image, presence: true
  has_many :comments, dependent:  :destroy
  has_many :users, through: :comments

  def next
    Post.where("id > ?", id).order(id: :asc).limit(1).first
  end

  def prev
    Post.where("id < ?", id).order(id: :desc).limit(1).first
  end
end

Desktop/Ruby/Ruby_on_Rails_Project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

Desktop/Ruby/Ruby_on_Rails_Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

Desktop/Ruby/Ruby_on_Rails_Project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id)
  end
end

Desktop/Ruby/Ruby_on_Rails_Project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    # @post = Post.new
    @post = current_user.posts.build
  end

  def create
    # @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, :notice => "Post Created Successfully!"
    else
      redirect_to new_post_path, :notice => "Something wents wrong, must fill all the fields"
    end
  end

  def show
      @post = Post.find(params[:id])
      @comments = Post.find(params[:id]).comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, :notice => "Post Updated Successfully!"
    else
      redirect_to edit_post_path , :notice => "Something wents wrong, must fill all the fields"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, :notice => "Post has been deleted"
  end

  def mypost
    @posts = Post.all
    @post_count = 0
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :user_id, :image)
  end

end

Desktop/Ruby/Ruby_on_Rails_Project/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/Ruby/Ruby_on_Rails_Project/app/helpers/comments_helper.rb
module CommentsHelper
end

Desktop/Ruby/Ruby_on_Rails_Project/app/helpers/posts_helper.rb
module PostsHelper
end

Desktop/Ruby/Ruby_on_Rails_Project/app/views/comments/_comment.html.erb
<div class="card bg-light">
  <div class="card-body">
    <% @comments.each do |c| %>
      <div class="d-flex">
        <div class="d-flex mb-4">
          <div class="flex-shrink-0">
            <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."/></div>
          <div class="ms-3">
            <div class="fw-bold"><%= c.user.email %></div>
            <%= c.body %>
          </div>
          <% if current_user == c.user or current_user == @post.user %>
            <div style="position: relative; left: 10px;bottom: 8px">
              <%= button_to "Delete", post_comment_path(c.post_id, c.id), method: :delete, class: "button is-ghost text-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div><br/>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |form| %>
  <div class="card bg-light">
    <div class="card-body">
      <div class="mb-4">
        <%= form.label :body, "Add a Comment", class: "subtitle fw-bold" %><br/>
        <%= form.text_area :body, class: "form-control", rows: "3", placeholder: "Join the discussion and leave a comment!" %>
        <br/>
        <%= form.submit 'Comment...', {class: "button is-link is-rounded"} %>
      </div>
    </div>
  </div>
<% end %>
<br/>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPost</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<!--  <p class="notice"><%#= notice %></p>-->
<!--  <p class="alert"><%#= alert %></p>-->

<%= render 'posts/header' %>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key} alert alert-success container" %>
<% end %><br/>

<%= yield %>
<%#= render 'posts/footer' %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/_footer.html.erb
<br/>
<div class="text-md-start py-4 px-4 px-xl-5 bg-primary mt-auto">
  <!-- Copyright -->
  <div class="text-white">
    Copyright © 2022. All rights reserved.
  </div>
</div>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/_header.html.erb
<nav class="navbar navbar-expand-lg container  bg-transparent">
  <div class="container-fluid">
    <%= link_to 'Blog Post', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item padding-navbar">
          <%= link_to 'Home', root_path, class: "nav-link active" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item padding-navbar">
            <%= link_to 'Create post', new_post_path, class: "nav-link active" %>
          </li>
          <li class="nav-item padding-navbar">
            <%= link_to 'My post', mypost_path(id: current_user.id), class: "nav-link active" %>
          </li>
        <% end %>
        <li class="nav-item padding-navbar">
          <%= link_to 'Contacts', '#', class: "nav-link active" %>
        </li>
        <li class="nav-item padding-navbar">
          <%= link_to 'About Us', '#', class: "nav-link active" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item padding-navbar">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item padding-navbar">
            <%= link_to 'Register', new_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item padding-navbar">
            <%= link_to 'Login', new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <div>
          <span class="nav-link active" style="color: black">
            Signed in as:<br/>
            <span><%= current_user.email %></span>
          </span>
        </div>
        <div class="padding-navbar">
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class: "btn btn-outline-primary rounded-pill", style: "padding: 10px 25px" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/about_us.html.erb
<h1 class="title is-1">From about Us</h1>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/contacts.html.erb
<h1 class="title is-1">From Contacts</h1>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/edit.html.erb
<div class="container">
  <div class="card-header text-white is-size-2" style="background-color: blue;height: 5rem;">
    Edit Post
  </div>
</div>
<br/>
<section class="container">
  <div class="card">
    <div class="card-body">
      <%= form_for @post do |form| %>
        <div class="container">
          <%= form.label :title, "Title", class: 'subtitle' %>
          <%= form.text_field :title, class: "input is-primary" %>
        </div>
        <br/><br/>
        <div class="container">
          <%= form.label :description, "Description", class: 'subtitle' %><br/>
          <%= form.text_area :description, class: "textarea is-primary" %>
        </div>
        <br/>
        <div class="container">
          <%= form.label :image, "Image Upload : ", class: "subtitle" %>
          <%= form.file_field :image %>
        </div>
        <br/>
        <div class="container buttons">
          <%= form.submit "Update post", class: "button is-danger" %>
          <%= link_to 'Back', @post, class: "button is-primary" %>
        </div>
        <br/>
      <% end %>
    </div>
  </div>
  <br/>
</section>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/index.html.erb
<div class="container" style="min-height: 76vh">
  <div class="row">
    <!-- Blog entries-->
    <div class="col-lg-12">
      <div class="title is-1">Welcome to Blog Post</div>
      <!-- Featured blog post-->
      <div class="card mb-6">
          <%= image_tag "main_post.jpg", {class: "card-img-top",alt: "...",style: "max-height: 500px;"} %>
        <div class="card-body text-justify">
          <h2 class="card-title fw-bold">Welcome to Blog Post!</h2>
          <p class="card-text">A blog is a discussion or informational website published on the World Wide Web consisting of discrete, often informal diary-style text entries (posts). Posts are typically displayed in reverse chronological order, so that the most recent post appears first, at the top of the web page. Until 2009, blogs were usually the work of a single individual,[citation needed] occasionally of a small group, and often covered a single subject or topic. In the 2010s, "multi-author blogs" (MABs) emerged, featuring the writing of multiple authors and sometimes professionally edited. MABs from newspapers, other media outlets, universities, think tanks, advocacy groups, and similar institutions account for an increasing quantity of blog traffic. The rise of Twitter and other "microblogging" systems helps integrate MABs and single-author blogs into the news media. Blog can also be used as a verb, meaning to maintain or add content to a blog.</p>
        </div>
      </div>
      <div class="row">
        <!-- Blog post-->
        <% @posts.each do |post| %>
          <div class="col-lg-4">
            <div class="card mb-4" style="height: 35rem">
              <%= link_to post do %>
                <%= image_tag post.image, class: "card-img-top", alt: "...", style: "max-height: 20rem;min-height: 15rem" %>
              <% end %>
              <div class="card-body text-justify" style="overflow: hidden;max-height: 80%;margin-bottom: 3.6rem">
                <div class="small text-muted">Posted on <%= post.created_at.to_formatted_s(:short) %></div>
                <h2 class="card-title h4"><%= post.title %></h2>
                <p class="card-text"><%= post.description %></p>
              </div>
              <div style="position: absolute;bottom: auto;right: 70%;">
                <%= link_to "Read more...", post, class: "btn btn-primary" %>
              </div>
              <div style="position: absolute;bottom: 10px;left: 70%;">
                <%= link_to "View post >>", post, class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'footer' %>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/mypost.html.erb
<h1 class="title is-2 container">My posts</h1>
<section class="container ">
  <% @posts.each do |post| %>
    <% if post.user == current_user %>
      <div class="card mb-3" style="height: 15rem; overflow: hidden;">
        <div class="row g-0">
          <div class="col-md-4">
            <%#= link_to post do %>
              <%= image_tag post.image, { class: "img-fluid rounded-start", alt: "...", style: "height: 15rem;width: 100%" } %>
            <%#= end %>
          </div>
          <div class="col-md-8 text-justify" style="max-height: 14rem;">
            <div class="card-body" style="overflow: hidden;max-height: 80%;margin-bottom: 70px">
              <h5 class="card-title h2"><%= post.title %></h5>
              <p class="card-text" ><%= post.description %></p>
              <p class="card-text" style="position: absolute;bottom: 10px">
                <small class="text-muted">Posted on <%= post.created_at.to_formatted_s(:short) %></small></p>
            </div>
          </div>
          <div style="position: absolute;bottom: 10px;left: 74rem">
            <%= link_to "Read more...", post, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      <% @post_count += 1 %>
    <% end %>

  <% end %>
</section>
<br/><br/>

<% if @post_count == 0 %>
  <div class="container">
    <p>There is no post to view</p><br/>
    <p><%= link_to 'Create new post', new_post_path %> to view</p>
  </div>
<% end %>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/new.html.erb
<div class="container">
  <div class="card-header text-white is-size-2" style="background-color: blue;height: 5rem;">Create new post</div>
</div>
<br/>
<section class="container">
  <div class="card">
    <div class="card-body">
      <%= form_for @post do |form| %>
        <div class="container">
          <%= form.label :title, "Title", class: 'subtitle' %>
          <%= form.text_field :title, class: "input is-info" %>
        </div><br/>
        <div class="container">
          <%= form.label :description, "Description", class: 'subtitle' %><br/>
          <%= form.text_area :description,class: "textarea is-info" %>
        </div><br/>
        <div class="container">
          <%= form.label :image, "Upload image : ",class: "subtitle" %>
          <%= form.file_field :image %>
        </div><br/>
        <div class="container">
          <%= form.number_field :user_id, id: :posts_user_id,value: current_user.id, type: :hidden %>
        </div>
        <div class="container">
          <%= form.submit "Create new post", class: "button is-link" %>
          <%= link_to 'Back', :back ,class: "button is-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</section>

Desktop/Ruby/Ruby_on_Rails_Project/app/views/posts/show.html.erb
<div class="container mt-5 " style="min-height: 76vh">
  <div class="row shadow p-3 mb-5 bg-white rounded mr-md-3">
    <div class="col-lg-12" style="margin: 10px;text-align: justify">
      <!-- Post content-->
      <article>
        <!-- Post header-->
        <header class="mb-4">
          <!-- Post title-->
          <h1 class="fw-bolder mb-1 title is-2"><%= @post.title %></h1>
          <% if user_signed_in? and @post.user == current_user %>
            <span style="position: absolute;right: 130px">
              <%= link_to 'Edit post', edit_post_path, class: "button is-danger is-light" %>
            </span>
            <span style="position: absolute;right: 30px">
              <%= button_to 'Delete', @post, :method => :delete, class: "button is-danger", confirm: "Are you sure?" %>
            </span>
          <% end %>
          <!-- Post meta content-->
          <div class="text-muted fst-italic mb-2">Posted on <%= @post.created_at.to_formatted_s(:short) %>by <%= @post.user.email %></div>
          <div>
          </div>
        </header>
        <!-- Preview image figure-->
        <div class="mb-4" style="width: 900px; height: auto">
          <%= image_tag @post.image, class: "img-fluid rounded", alt: "...", style: " width: 50%" %>
        </div>
        <!-- Post content-->
        <div class="mb-12" style="margin-right: 15px">
          <p style="text-align: justify-all"><%= @post.description %></p>
        </div>
      </article>
    </div>
  </div>
  <div class="buttons is-justify-content-center">
    <%= link_to "<< Prev Post", @post.prev, class: "button is-primary" %>
    <%= link_to "Next Post >>", @post.next, class: "button is-link" %>
  </div>
  <% if user_signed_in? %>
    <h2 class="title is-4 fw-bold"><%= @post.comments.count %> Comments</h2>
    <%= render 'comments/form' %>
    <% if @post.comments.count > 0 %>
      <%= render 'comments/comment' %>
    <% end %>
  <% end %>
</div>

<%= render 'footer' %>